cam_specs: {
  'depth_front': {
    'x': 2.36, 'y': 0.0, 'z': 1.5,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'type': 'sensor.camera.depth',
  },
  'depth_front_left': {
    'x': 2.36, 'y': -0.792, 'z': 1.5,
    'roll': 0.0, 'pitch': 0.0, 'yaw': -55.0,
    'type': 'sensor.camera.depth',
  },
  'depth_front_right': {
    'x': 2.36, 'y': 0.792, 'z': 1.5,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 55.0,
    'type': 'sensor.camera.depth',
  },
  'depth_back': {
    'x': -2.36, 'y': 0.0, 'z': 1.55,
    'roll': 0.0, 'pitch': 0.0, 'yaw': -180.0,
    'type': 'sensor.camera.depth',
  },
  'depth_back_left': {
    'x': -2.36, 'y': -0.792, 'z': 1.55,
    'roll': 0, 'pitch': 0.0, 'yaw': -110,
    'type': 'sensor.camera.depth',
  },
  'depth_back_right': {
    'x': -2.36, 'y': 0.792, 'z': 1.55,
    'roll': 0, 'pitch': 0.0, 'yaw': 110,
    'type': 'sensor.camera.depth',
  },
  'camera_front': {
    'x': 2.36, 'y': 0.0, 'z': 1.5,
    'fov': 100,
    'roll': 0, 'pitch': 0, 'yaw': 0,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_front_left': {
    'x': 2.36, 'y': -0.792, 'z': 1.5,
    'fov': 100,
    'roll': 0.0, 'pitch': 0.0, 'yaw': -55.0,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_front_right': {
    'x': 2.36, 'y': 0.792, 'z': 1.5,
    'fov': 100,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 55.0,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_back': {
    'x': -2.36, 'y': 0.0, 'z': 1.55,
    'fov': 100,
    'roll': 0.0, 'pitch': 0.0, 'yaw': -180.0,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_back_left': {
    'x': -2.36, 'y': -0.792, 'z': 1.55,
    'fov': 100,
    'roll': 0, 'pitch': 0.0, 'yaw': -110,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_back_right': {
    'x': -2.36, 'y': 0.792, 'z': 1.55,
    'fov': 100,
    'roll': 0, 'pitch': 0.0, 'yaw': 110,
    'type': 'sensor.camera.rgb',
    'width': 400,
    'height': 300,
  },
  'camera_video_purpose': {
    'x': -10, 'y': 0, 'z': 5,
    'fov': 70,
    'roll': 0, 'pitch': -20.0, 'yaw': 0,
    'type': 'sensor.camera.rgb',
    'width': 1600,
    'height': 900,
  },
}
lidar_specs: {
  'lidar_01': {
    'x': -20.0, 'y': -20.0, 'z': 10,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'channels': 160, 'range': 50, 'points_per_second': 1000000,
    'rotation_frequency': 100, 'type': 'sensor.lidar.ray_cast',

    'horizontal_fov': 360,
    'upper_fov': 0,
    'lower_fov': -90,
  },
  'lidar_02': {
    'x': -20.0, 'y': 20.0, 'z': 10,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'channels': 160, 'range': 50, 'points_per_second': 1000000,
    'rotation_frequency': 100, 'type': 'sensor.lidar.ray_cast',

    'horizontal_fov': 360,
    'upper_fov': 0,
    'lower_fov': -90,
  },
  'lidar_03': {
    'x': 20.0, 'y': -20.0, 'z': 10,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'channels': 160, 'range': 50, 'points_per_second': 1000000,
    'rotation_frequency': 100, 'type': 'sensor.lidar.ray_cast',

    'horizontal_fov': 360,
    'upper_fov': 0,
    'lower_fov': -90,
  },
  'lidar_04': {
    'x': 20.0, 'y': 20.0, 'z': 10,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'channels': 160, 'range': 50, 'points_per_second': 1000000,
    'rotation_frequency': 100, 'type': 'sensor.lidar.ray_cast',

    'horizontal_fov': 360,
    'upper_fov': 0,
    'lower_fov': -90,
  },
  'lidar_05': {
    'x': 0.0, 'y': 0.0, 'z': 10,
    'roll': 0.0, 'pitch': 0.0, 'yaw': 0.0,
    'channels': 160, 'range': 50, 'points_per_second': 1000000,
    'rotation_frequency': 100, 'type': 'sensor.lidar.ray_cast',

    'horizontal_fov': 360,
    'upper_fov': 0,
    'lower_fov': -90,
  }
}